FROM openjdk:8u212-jdk-slim

LABEL maintainer="yogendra.yadav@nagarro.com"

VOLUME /tmp

ARG JAR_FILE=target/userservice-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} userservice.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/userservice.jar"]

EXPOSE 8081